Repository openSUSE/doc-kit, pull requests merged in 2023-11, with the labels that each got.

#74 Remove DocBook 4 dependency (entities)
  docbook5-book/xml/generic-entities.ent
Labels: cat-enhancement, scope-template

#82 Sort DocBook 4 entities
  entities/generic-entities.ent
Labels: cat-enhancement

#83 Added upstream-updated files to .gitignore
  .gitignore
  bin/doc-kit
  smart-doc/common/legal.xml
Labels: cat-enhancement

#84 Smart Docs metadata: Amend assembly file with meta information
  smart-doc/articles/assembly.asm.xml
  smart-doc/common/legal.xml
Labels: cat-enhancement, kit-smartdoc
